name: Automated API Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Running Test Scenario
      continue-on-error: true
      run: apidog run --access-token ${{secrets.APIDOG_ACCESS_TOKEN}} -t 5079 -e 6528501 -n 1 -r html,cli
